var CwtAceEditor=Class.create();
CwtAceEditor.prototype={initialize:function(a,d){var c=$(a).offsetParent;this.objectName=a;this.options=d;window.formValuesListener[window.formValuesListener.length]=this;window.aceEditor=ace.edit(this.objectName);window.aceEditor.setTheme("ace/theme/eclipse");d?(d.language&&(a=require("ace/mode/"+d.language).Mode,window.aceEditor.getSession().setMode(new a)),d.height?$(this.objectName).style.height=d.height:(c=null===c?$("ajax_tabContent").offsetHeight-50:window.document.body.offsetHeight-getCumulativeOffsetTop($(this.objectName))-
15,$(this.objectName).style.height=c+"px"),this.objectName.fontSize?this.setAceFontSize(d.fontSize):this.setAceFontSize("12px"),d.matchAttribute&&(this.matchAttribute=d.matchAttribute,this.onCursorChange=this.checkMatchAttribute.bind(this),window.aceEditor.getSession().selection.on("changeCursor",this.onCursorChange))):(this.setAceFontSize("12px"),c=null===c?$("ajax_tabContent").offsetHeight-50:window.document.body.offsetHeight-getCumulativeOffsetTop($(this.objectName))-15,$(this.objectName).style.height=
c+"px");window.aceEditor.focus();window.aceEditor.resize();window.aceEditor.getSession().setUseWrapMode(!1);window.aceEditor.getSession().setWrapLimitRange();window.aceEditor.setShowPrintMargin(!1);window.aceEditor.setHighlightActiveLine(!1)},checkMatchAttribute:function(){var a=window.aceEditor.getCursorPosition(),d=window.aceEditor.getSession().getLine(a.row),c=d.split(new RegExp(this.matchAttribute+'\x3d"(.*)"'));if(1<c.length){var b=document.createElement("lContent");b.innerHTML=d;for(var e,f=
0;f<b.childNodes.length;f++){var g=b.childNodes[f];1==g.nodeType&&g.getAttribute(this.matchAttribute)&&(e=g)}e&&(d.indexOf(c[1]),window.parent.eventHandler(null,"stringMatch",encodeURIComponent(this.objectName),"A",this,[e.getAttribute(this.matchAttribute),a.row]))}},setAceFontSize:function(a){window.aceEditor.renderer.$textLayer.element.style.fontSize=a;window.aceEditor.setFontSize(a)},createMaximizeIcon:function(a){function d(b,e){for(;b.className!=e;)if(b=b.parentNode,!b)return null;return b}var c=
$(a);c.style.position="relative";c.style.top=null;c.style.left=null;c=$(this.objectName+"_maximize");Event.observe(c,"click",function(b){b=$(b);b.style.zIndex="10";var e=$$("[class*\x3dtitleBar]")[0],f=$$("[class*\x3dparent-managefiles-info-label]")[0],g=$$("[class*\x3dCwtAceEditorToolbar]")[0],h=$$("[class*\x3dfooter]")[0],k=$(this.objectName+"_maximize");k.style.visibility="hidden";k.style.width="0px";k=$(this.objectName+"_minimize");k.style.visibility="visible";k.style.width="18px";e=e?e.getBoundingClientRect().height:
0;f=f?f.getBoundingClientRect().height:0;g=g?g.getBoundingClientRect().height:0;h=h?h.getBoundingClientRect().height:0;h=getClientHeight()-(40+e+f+g+h);this.oldHeight=$(this.objectName).style.height;$(this.objectName).style.height=h+"px";$(this.objectName).style.width="100%";(h=d(b,"modal-inner-title"))?(h.addClassName("ace-maximize"),b.style.top="0px",b.style.left="0px",b.style.width="100%",b=getClientHeight()-viewportOffset($(this.objectName))[1],$(this.objectName).style.height=b+"px"):(b=d(b,"parent-content-wrapper"))&&
b.addClassName("ace-maximize-wrapper");window.aceEditor.resize()}.bind(this,a));c=$(this.objectName+"_minimize");Event.observe(c,"click",function(b){b=$(b);b.style.zIndex="0";var e=$(this.objectName+"_minimize");e.style.visibility="hidden";e.style.width="0px";e=$(this.objectName+"_maximize");e.style.visibility="visible";e.style.width="18px";$(this.objectName).style.height=this.oldHeight;(e=d(b,"modal-inner-title ace-maximize"))?e.removeClassName("ace-maximize"):(b=d(b,"parent-content-wrapper ace-maximize-wrapper"))&&
b.removeClassName("ace-maximize-wrapper");window.aceEditor.resize()}.bind(this,a));c.style.visibility="hidden";c.style.width="0px"},updateFormValues:function(){var a=$(this.objectName+".data");a&&(a.value=window.aceEditor.getSession().getValue())},goToLine:function(a){window.aceEditor.gotoLine(a)},undo:function(){window.aceEditor.undo()},redo:function(){window.aceEditor.redo()},search:function(a){window.aceEditor.find(a)},setReadOnly:function(a){window.aceEditor.setReadOnly(a)},replace:function(a){window.aceEditor.navigateLeft(1);
window.aceEditor.replace(a)},zoomIn:function(a){this.setAceFontSize(parseInt($(this.objectName).style.fontSize,10)+1+"px")},zoomOut:function(a){this.setAceFontSize(parseInt($(this.objectName).style.fontSize,10)-1+"px")},insertTextAtCursor:function(a){window.aceEditor.insert(a);window.aceEditor.focus()},replaceAtLine:function(a,d,c){window.aceEditor.gotoLine(c);window.aceEditor.find(a);window.aceEditor.replace(d)},activateWrapMode:function(a){window.aceEditor.getSession().setUseWrapMode(!0);window.aceEditor.getSession().setWrapLimitRange(null,
null)},deactivateWrapMode:function(a){window.aceEditor.getSession().setUseWrapMode(!1);window.aceEditor.getSession().setWrapLimitRange()}};